### ISSUE TITLE
Private symbol server support

### ISSUE THREAD

**Issue by mycroes** [SimonCropp/Cymbal#4]
#### Is the feature request related to a problem

Cymbal currently doesn't download from private symbol servers. That's outlined in the readme and I see no mention (in documentation) of any way to change this behavior.

#### Describe the solution

Support downloading symbols from private symbol servers by permitting the user to specify the symbol server in a MSBuild property.

#### Describe alternatives considered

None, I can't think of an alternative for this issue.

#### Additional context

This permits private packages to be used where NuGet packages and symbols are on a private symbol server. I like this approach to packaging (the split packages), but I'm now missing the PDB files in production which reduces usability of logs and exception stack traces.

**Comment by SimonCropp** [comment]
so this is for your own internal nugets?

**Comment by mycroes** [comment]
Yes, preparing PR as we speak
