### ISSUE TITLE
Support filtering of files to consume

### ISSUE THREAD

**Issue by mycroes** [SimonCropp/Cymbal#5]
#### Is the feature request related to a problem

Cymbal will now search for symbols for all dlls, while I don't necessarily want pdb files for Microsoft packages in production. I do however want company private packages to have their symbols included, adding a filter option would permit this.

#### Describe the solution

A filter based on filename using MSBuild properties would enable users to selectively get the desired symbols only.

#### Describe alternatives considered

Letting Cymbal download the symbols and delete them afterwards.

#### Additional context

-

**Comment by mycroes** [comment]
#6 in it's current form permits what I desire: if you only specify the private symbol server it will only download symbols there and omit other sources.

**Comment by SimonCropp** [comment]
so give #6 is merged can we close this?

> while I don't necessarily want pdb files for Microsoft packages in production

i dont know why you would not want them?

**Comment by mycroes** [comment]
I still think this is a valid feature, but my itch is scratched with #6 merged. As far as excluding Microsoft packages, I trust I'm making the errors in my own code and someone else will run into issues with Microsoft packages before I will. I guess there can be exceptions, but on average the errors will be in my own code, not in libraries used.

**Comment by SimonCropp** [comment]
happy to consider a pull request for this

**Comment by mycroes** [comment]
May I ask how this is implemented? I don't see any recent changes relating to this. Or did you close it due to lack of demand?

**Comment by SimonCropp** [comment]
@mycroes 

> happy to consider a pull request for this

assuming since no one submitted a PR, no one wants it enough

i dont need it. if you need it, and dont have capacity to implement, i am happy to accept some $$ to work on it

**Comment by mycroes** [comment]
Thanks for the update. I agree entirely. As I said, my itch is scratched with the separate server support. I'd be happy to implement it if the need arises, but I also have tons of other projects I (want to) work on. I'm also not in the position to pay you for said feature (or sponsor you for building Cymbal in the first place, which is worth just as much I'd think), the only thing I have to offer is time and that hugely depends on priorities. Either way, good to have this clarified, the next person looking for this knows what to do 😉
